l1=['abcd',147,3.14,'tom',749]
l2=[111,'tom']
print("first list(l1):",l1)
print("0 th index(first) element of list(l1):",l1[0])
print("1st and 2nd index element of list(l1):",l1[1:3])
print("list multiplication:",l2*2)
print("list concatenation:",l1+l2)
print("list before deletion:",l1)
del l1[1]
print("list after deletion:",l1)
l3=[119,147,2,43,234,749]
print("total number of elements in list:",len(l3))
print("largest element in list:",max(l3))
print("smallest element in list:",min(l3))
l3.reverse()
print("reversing the list")
print("list after reversing:",l3)
print("counting number of element 749 in list:",l3.count(749))
print("------------------------------------------")
print("stack operations:")
print("list before appending:",l3)
l3.append(749)
print("list after appending:",l3)
l3.pop(2)
print("poping element in 2nd index")
print("list after poping:",l3)
l3.remove(749)
print("removing element 749 from the list")
print("list after removing:",l3)
print("------------------------------------------")
l3.insert(4,20)
print("inserting the element 20 in the 4th position:")
print("list after insertion:",l3)
l3.sort()
print("sorting the list")
print("list after sorting:",l3)
l3.sort(reverse=True)
print("sorting the list and reversing it")
print("list after sorting and reversing it:",l3)
print("index of element 749 in list:",l3.index(749))
l3.copy()
print("creating copy of the list")
print("copy of the list:",l3)
l3.clear()
print("clearing the list")
print("list after clearing:",l3)
